# Generated by Django 5.1.2 on 2024-10-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.BigIntegerField(db_comment="支払金額")),
                ("tax", models.IntegerField(db_comment="税額")),
                ("total_amount", models.IntegerField(db_comment="総支払額")),
                ("payment_at", models.DateTimeField(db_comment="支払日")),
                (
                    "user_country_code",
                    models.CharField(db_comment="ユーザーの国コード", max_length=255),
                ),
                (
                    "user_email",
                    models.CharField(
                        db_comment="ユーザーのメールアドレス", max_length=255
                    ),
                ),
                (
                    "user_name",
                    models.CharField(db_comment="ユーザーの名前", max_length=255),
                ),
                (
                    "user_post_code",
                    models.CharField(db_comment="ユーザーの郵便番号", max_length=255),
                ),
                (
                    "user_prefecture",
                    models.CharField(db_comment="ユーザーの都道府県", max_length=255),
                ),
                (
                    "user_address1",
                    models.CharField(db_comment="ユーザーの住所1", max_length=255),
                ),
                (
                    "user_address2",
                    models.CharField(db_comment="ユーザーの住所2", max_length=255),
                ),
                (
                    "user_tel1",
                    models.CharField(db_comment="ユーザーの電話番号1", max_length=15),
                ),
                (
                    "user_tel2",
                    models.CharField(db_comment="ユーザーの電話番号2", max_length=15),
                ),
                (
                    "company_country_code",
                    models.CharField(db_comment="会社の国コード", max_length=255),
                ),
                (
                    "company_name",
                    models.CharField(db_comment="会社の名前", max_length=255),
                ),
                (
                    "company_post_code",
                    models.CharField(db_comment="会社の郵便番号", max_length=255),
                ),
                (
                    "company_prefecture",
                    models.CharField(db_comment="会社の都道府県", max_length=255),
                ),
                (
                    "company_address1",
                    models.CharField(db_comment="会社の住所1", max_length=255),
                ),
                (
                    "company_address2",
                    models.CharField(db_comment="会社の住所2", max_length=255),
                ),
                (
                    "company_tel1",
                    models.CharField(db_comment="会社の電話番号1", max_length=15),
                ),
                (
                    "company_tel2",
                    models.CharField(db_comment="会社の電話番号2", max_length=15),
                ),
                (
                    "stripe_code",
                    models.CharField(
                        db_comment="Stripeのコード", max_length=255, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "db_table_comment": "支払い",
            },
        ),
    ]
