# Generated by Django 5.1.2 on 2024-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.CharField(
                        db_comment="メールアドレス", max_length=255, unique=True
                    ),
                ),
                ("password", models.CharField(db_comment="パスワード", max_length=255)),
                (
                    "is_active",
                    models.BooleanField(db_comment="アクティブかどうか", default=True),
                ),
                ("name", models.CharField(db_comment="名前", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日時"),
                ),
            ],
            options={
                "db_table": "admin_users",
                "db_table_comment": "管理者ユーザー",
            },
        ),
    ]
