# Generated by Django 5.1.2 on 2024-10-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_comment="チャットルームUUID", max_length=255, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(db_comment="チャットルーム名", max_length=255),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        db_comment="最終メッセージ日時", db_index=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="chat_rooms",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "chat_rooms",
                "db_table_comment": "チャットルーム",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("message", models.TextField(db_comment="メッセージ内容")),
                ("message_token", models.IntegerField(db_comment="メッセージタイプ")),
                (
                    "role",
                    models.CharField(db_comment="メッセージの役割", max_length=255),
                ),
                (
                    "ai_model_name",
                    models.CharField(db_comment="AIモデル名", max_length=255),
                ),
                (
                    "ai_model_version",
                    models.CharField(db_comment="AIモデルバージョン", max_length=255),
                ),
                (
                    "ai_model_provider",
                    models.CharField(db_comment="AIモデルプロバイダー", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日時"),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="chat_messages",
                        to="chats.chatroom",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "db_table_comment": "チャットメッセージ",
            },
        ),
    ]
