# Generated by Django 5.1.2 on 2024-10-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.CharField(
                        db_comment="メールアドレス", max_length=255, unique=True
                    ),
                ),
                ("password", models.CharField(db_comment="パスワード", max_length=255)),
                (
                    "is_active",
                    models.BooleanField(db_comment="アクティブかどうか", default=True),
                ),
                ("name", models.CharField(db_comment="名前", max_length=255)),
                ("post_code", models.CharField(db_comment="郵便番号", max_length=255)),
                (
                    "country_code",
                    models.CharField(db_comment="国コード", max_length=255),
                ),
                ("prefecture", models.CharField(db_comment="都道府県", max_length=255)),
                ("address1", models.CharField(db_comment="住所1", max_length=255)),
                ("address2", models.CharField(db_comment="住所2", max_length=255)),
                ("tel1", models.CharField(db_comment="電話番号1", max_length=15)),
                ("tel2", models.CharField(db_comment="電話番号2", max_length=15)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日時"),
                ),
            ],
            options={
                "db_table": "users",
                "db_table_comment": "ユーザー",
            },
        ),
        migrations.CreateModel(
            name="UserMessageCount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("total_count", models.BigIntegerField(db_comment="メッセージ数")),
                ("this_month_count", models.BigIntegerField(db_comment="メッセージ数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日時"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="user_message_count",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_message_counts",
                "db_table_comment": "ユーザーメッセージ数",
            },
        ),
    ]
